FROM docker.elastic.co/logstash/logstash-oss:7.0.0

# Example plugin installation:
# RUN bin/logstash-plugin install logstash-input-rss

COPY logstash/logstash.conf /usr/share/logstash/pipeline/logstash.conf