version: '3'
services:
  logstash:
    image: logstash
    build:
      context: .
      dockerfile: Dockerfile.Logstash
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
    restart: always
volumes:
  esdata1:
    driver: local